# mapping mode
temporary_mapping: true
accumulative_mapping: false

OccupancyGridMap:
    CellSize: 0.02
    EnablePosesTrimmer: false
    LocalMapBuilder:
        # CellSize
        MaxVisibleRange: 4.0
        EnableRayTracing: true
        RayTracing:
            # CellSize
            MaxVisibleRange: 4.0
            MaxTracingRange: 4.0
            TraceIntoUnknownSpace: true
        MaxRange2d: -1.0
    EnableObjectTracking: false

