map_frame: local_map_lidar
updated_poses_frame: base_link

needs_localization: true

# mapping mode
accumulative_mapping: true
temporary_mapping: false

# door tracking
door_tracking_small_radius: 0.3
door_tracking_large_radius: 0.7
draw_door_center_estimation: false
draw_door_corners: false


### Rtabmap parameters

Grid/CellSize: 0.10
Grid/MissProb: 0.4
Grid/HitProb: 0.7
Grid/MinClampingProb: 0.1192
Grid/MaxClampingProb: 0.971
Grid/OccupancyThr: 0.5
Grid/TemporarilyOccupiedCellColor: 9831741  # 9831741
Grid/ShowTemporarilyOccupiedCells: true
Grid/TemporaryMissProb: 0.4
Grid/TemporaryHitProb: 0.7
Grid/TemporaryOccupancyThr: 0.5
Grid/MaxTemporaryLocalMaps: 1

TimedGrid/MaxInterpolationTimeError: 0.06
TimedGrid/GuaranteedInterpolationTimeWindow: 1.0

LocalMap/MaxVisibleRange: 0.0
LocalMap/MaxRange2d: 10.0
LocalMap/MinObstacleHeight: 0.2
LocalMap/MaxObstacleHeight: 1.2
LocalMap/MinSemanticRange: 0.0
LocalMap/MaxSemanticRange: 0.0
LocalMap/UseRayTracing: true
LocalMap/SensorBlindRange2d: 0.0

SemanticDilation/DilationSize: 20
ObstacleDilation/DilationSize: 0.0

RayTracing/MaxVisibleRange: 100.0
RayTracing/MaxRayTracingRange: 10.0
RayTracing/TraceRaysIntoUnknownSpace: false
