map_frame: local_map_lidar

cache_map: true
needs_localization: true
max_interpolation_time_error: 0.06
update_max_extrapolation_time: 1

# mapping mode
accumulative_mapping: false
temporary_mapping: true

# door tracking
door_tracking_small_radius: 0.3
door_tracking_large_radius: 0.7
draw_door_center_estimation: false
draw_door_corners: false


### Rtabmap parameters

Grid/CellSize: 0.02
GridGlobal/MissProb: 0.4
GridGlobal/HitProb: 0.7
GridGlobal/MinClampingProb: 0.1192
GridGlobal/MaxClampingProb: 0.971
GridGlobal/OccupancyProbThr: 0.5
GridGlobal/TemporarilyOccupiedCellColor: 9831741  # 9831741
GridGlobal/ShowTemporarilyOccupiedCells: true
Grid/TemporaryMissProb: 0.4
Grid/TemporaryHitProb: 0.7
Grid/TemporaryOccupancyProbThr: 0.5
Grid/MaxTemporaryLocalMaps: 1

LocalMap/MaxVisibleRange: 4.0
LocalMap/MaxRange2d: 0.0
LocalMap/MinObstacleHeight: 0.2
LocalMap/MaxObstacleHeight: 1.5
LocalMap/MinSemanticRange: 0.0
LocalMap/MaxSemanticRange: 0.0
LocalMap/UseRayTracing: true
LocalMap/SensorBlindRange2d: 0.0

SemanticDilation/DilationSize: 20
ObstacleDilation/DilationSize: 0.0

RayTracing/MaxVisibleRange: 4.0
RayTracing/MaxRayTracingRange: 4.0
RayTracing/TraceRaysIntoUnknownSpace: true
